ENH: Auto-disable AVX optimisation for Intel compiler if kernel too old
     SandyBridge-EP processors support AVX which is why we used to set
     -xAVX to enable all appropriate optimisations for such processors
     with Intel compilers >= 11.1. Unfortunately, AVX support also
     hinges on kernel features only available from 2.6.30 onwards.
     SuSE Linux Enterprise 11 <= SP2, Red Hat Enterprise Linux 5.x,
     CentOS <= 6.1 and other Linux distributions have older kernels such
     that compiling with -xAVX worked, but execution of the resulting
     binaries led to

       Fatal Error: This program was not built to run in your system.
       Please verify that both the operating system and the processor
       support Intel(R) AVX.

     To overcome this, the build system now queries the kernel for
     availability of AVX features if build ID is
     pc*-sandybridge_ep-intel-* and enables all optimisations that -xAVX
     would have enabled except for the AVX optimisations.

     There is a catch with this approach, though: The auto-disabling
     does not work in case of cross-compilation. Even worse, when
     cross-compiling using a processor that *has no* AVX capabilities
     for a SandyBridge-EP processor and a kernel that is *recent
     enough*, AVX optimisations will still be disabled. Which is why a
     warning is raised whenever missing AVX support is detect for build
     IDs pc*-sandybridge_ep-intel-*