COMP: Flagship application compiles again.
      Fixed syntax error:
        if (not(present(rconsistentMassMatrix)) ...
      =>
        if (.not.(present(rconsistentMassMatrix)) ...
      which caused mails about benchmark applications compilation errors last night.