COMP: Fixed problem with gfortran compiler
      The gfortran compiler does not compile the following code

      module storage
        ...
        use iso_c_binding
	implicit none

	private
	public :: c_ptr,c_null_ptr
	...
      end module storage

      but complains about:
      Error: PARAMETER attribute conflicts with SAVE attribute in 'c_null_ptr' at (1)

      IMHO, this is a compiler bug (and all other tested compilers do
      accept this code). Since c_null_ptr is only used in the storage
      module it is not necessary to export it by making it public.